### ISSUE TITLE
When you drop Enabled effects they aren't reordered properly.

### ISSUE THREAD

**Issue by mattfg** [pmeas/pmeas-frontend#41]
![image](https://cloud.githubusercontent.com/assets/9244059/23594466/49a256f4-01e8-11e7-8fe4-b6157a4c00dd.png)

Difference between this and #15 is that this is about the way rearranged effects are _displayed_ and #15 is about them being assigned the correct "order number"

**Comment by joshwahwalters** [comment]
This issue should be solved when issue #15 is implemented.

**Comment by Druage** [comment]
Sadly this issue is still not fixed, mainly because I didn't even think about it. This can be addressed this week.

**Comment by mattfg** [comment]
"still not fixed" I created it like an hour ago lee lol

**Comment by Druage** [comment]
I mean't issue in a general sense, not specifically referring to a Github issue.
